[package]
name = "packet-ipc"
version = "0.1.0"
authors = ["Danny Browning <danny.browning@protectwise.com>"]
edition = "2018"

[dependencies]
bincode = "~1.0"
crossbeam-channel = "~0.3"
failure = "~0.1"
failure_derive = "~0.1"
futures-preview = { version ="0.3.0-alpha.11", features = ["compat"] }
ipc-channel = "~0.11"
log = "~0.4"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"

[dev-dependencies]
env_logger = "~0.6"
