[package]
name = "packet-ipc"
version = "0.1.0"
authors = ["Danny Browning <danny.browning@protectwise.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "~0.3"
error-chain = "~0.12"
futures = "~0.1"
ipc-channel = "~0.11"
log = "~0.4"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"

[dev-dependencies]
env_logger = "*"
